# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 912429fac35e6387a5ee764149c4b9b0220c61dfc7cc00782a52cf5b1dce1042d44fad7a58e321df6b360369470b6afb3a8c4499a2c6ef71389aa1b8144db373

test:
  secret_key_base: 523a5e260eb3a3ffdc3cc01fcc170fa3dc6b6011b42ed38f0c7228653347247ed8730070702b2de713a78d7c4a8b8a50bbb7049124da64407241125dc7cdfd87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
